### PR TITLE
Updated to BN256

### PR DESCRIPTION
**Pull request by jot2re**
Updated the code to use BN256 group 1 instead of SECP256k1.
NOTE: testContract fails since the solidity is not updated. I think @JamesSmartCell has to do this.

Parameters for BN256 group 1 are as follows:
Field Size: 115792089237314936872688561244471742058375878355761205198700409522629664518163
Curve order: 115792089237314936872688561244471742058035595988840268584488757999429535617037
h (cofactor): 1
For equation y^2=x^3+ax+b:
a: 0
b: 3

### CODE REVIEW

**Comment by colourful-land** [comment]
I'll leave this open until @JamesSmartCell updated the contract.

**Comment by jot2re** [comment]
Still work in progress, since we need to change to Pedersen commitments

**Comment by colourful-land** [comment]
Thanks a lot - closely monitoring progress on this as we originally set the delivery of issuer (ticket isssuer class ) by end of Dec.

**Comment by jot2re** [comment]
I have updated this to use Pedersen commitments to prevent possible brute forcing of user ID when using pairing based elliptic curves for the math.

**Review by colourful-land — APPROVED** [review]
Builds fine…

**Pull request merged**
