### PR TITLE
Devcon

### PR DESCRIPTION
**Pull request by micwallace**
This adds support for validation against multiple public keys for a single conference ID

### CODE REVIEW

**Review by oleggrib — APPROVED** [review]
It works! thank you.

**Comment by jot2re** [comment]
@micwallace it looks good, but would be nice with a negative test validating that keys from "wrong" conferences cannot be used to verify. I.e. that a key for Devcon 6 cannot be used to validate a signature on a ticket issued for Devcon 5.

**Comment by jot2re** [comment]
Note that the reason the tests fail is not because of the change, but because the smart contract integration tests fails due to obsolescence of Rinkeby

**Review by oleggrib — APPROVED** [review]
looks good, thank you, @micwallace

**Pull request merged**
