### PR TITLE
fix: 🐛 process undefined fix, upgraded modules for audit

### PR DESCRIPTION
**Pull request by oleggrib**
✅ Closes: TKS-961
partial fix for [TKS-959](https://smarttokenlabs.atlassian.net/browse/TKS-959)
@nicktaras 

Michael, could you check and deploy if all looks good? Thank you

[TKS-959]: https://smarttokenlabs.atlassian.net/browse/TKS-959?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by micwallace — APPROVED** [review]
@oleggrib thanks mate. I came across the same issue while testing. Was going to fix it tomorrow but you beat me to it!

**Comment by micwallace** [comment]
Audit is still failing. Maybe need to check package-lock.json into git?

**Review by micwallace — APPROVED** [review]

**Review by nicktaras — APPROVED** [review]

**Comment by micwallace** [comment]
@oleggrib I still can't merge because unit test results aren't being reported even though tests passed. 

I have published v0.4.3 until @abcfy2 can have a look.

**Comment by nicktaras** [comment]
@oleggrib & @micwallace, thanks for this change.

I've merged this from checking with Oleh around the PR & CICD status (the checks that could not complete) at the time of the merge.

Based on this with the with approvals, from myself and Miccy - the merge was applied.

Thanks again guys.

**Pull request merged**
