### PR TITLE
MetaMask signing of NFTAttestation looks weird

### PR DESCRIPTION
**Pull request by jot2re**
This fixes issue #201

### CODE REVIEW

**Review by oleggrib — COMMENTED** [review]
@jot2re code looks good. Js code updated accordingly.

Maybe worth to add some template for message hash? Like "Please sign message 'a8c755bb...' to prove that you own NFTs." or something similar. 

As option - we can send message template as input string to make it flexible.

**Comment by jot2re** [comment]
I have added support for prefix/postfix message for the hash that gets signed. 
I also adjusted to have both a version 1 and 2 type of signature as per the discussion [here](https://github.com/AlphaWallet/AlchemyNFT/issues/143)

However, this PR is not sufficient by its own to make a new release. For this issue #203 should also be implemented. 
Once this is merged, I will continue working on issues #203.

**Comment by jot2re** [comment]
@oleggrib I see that for some reason a conflict has occurred in the type script files. Can you check up on that and merge afterwards if you agree with everything?

**Comment by jot2re** [comment]
Looks good

**Pull request merged**
