### PR TITLE
test-case failures (should be captured by CI)

### LINKED ISSUE #147: build failed with eip712 errors + using deprecated API in IdentifierAttestation.java
````
$ java --version
openjdk 14.0.2 2020-07-14
$ gradle build

> Task :compileJava
Note: /home/vnaeli/IdeaProjects/attestation/src/main/java/com/alphawallet/attestation/IdentifierAttestation.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :test

TestAttestationUsageEip712 > otherTimeLimit() FAILED
    org.opentest4j.AssertionFailedError at TestAttestationUsageEip712.java:103

TestAttestationUsageEip712 > testDecoding() FAILED
    org.opentest4j.AssertionFailedError at TestAttestationUsageEip712.java:112

Eip712Test > referenceEncodingOtherOrder() FAILED
    org.opentest4j.AssertionFailedError at Eip712Test.java:58

Eip712Test > referenceEncoding() FAILED
    org.opentest4j.AssertionFailedError at Eip712Test.java:73

228 tests completed, 4 failed
````

### PR DESCRIPTION
**Pull request by colourful-land**
this is my attempt to solve #147. There were 4 test cases that failed on my PC - in the future we should detect such with CI - I only had the knowledge/time to fix 1 out of the 4 (committed). The rest look mysterious, for example, `public void referenceEncoding()` in `./src/test/java/org/tokenscript/eip712/Eip712Test.java` which show a discrepancy between the expected signature and the actual one produced by the test-case.

it should also fix #147 after previous PR introduced CI which erred.

### CODE REVIEW

**Review by jot2re — APPROVED** [review]
Looks good

**Comment by jot2re** [comment]
I tried running on Java 11 and and Java 8. Both also works perfectly on my machine (which is a Mac running Big Sur)

**Comment by jot2re** [comment]
I have tried a possible fix (it is hard for me to test, since things don't fail on my machine). See #147 for details.

**Comment by colourful-land** [comment]
didn't work. even with c443aa3359461126d4e9c18dc9356465afb485c6 I still got this:

````
> Task :test
jul. 05, 2021 7:10:12 P. M. org.junit.platform.launcher.core.EngineDiscoveryOrchestrator lambda$logTestDescriptorExclusionReasons$7
INFORMACIÓN: 0 containers and 18 tests were Method or class mismatch

expected: <{"signatureInHex":"0x71d1b3925bcc1482e34f4ae6f5560e27e6a7f3ad48acefb8089f3d450b3b6e225f28d2a73f1b08956e5b75c5ff0552e251492b493849aac8f4a9cd8cc54bee231c","jsonSigned":"{\"types\":{\"Test\":[{\"name\":\"payload\",\"type\":\"string\"},{\"name\":\"description\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":\"string\"}],\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"},{\"name\":\"verifyingContract\",\"type\":\"address\"},{\"name\":\"salt\",\"type\":\"bytes32\"}]},\"primaryType\":\"Test\",\"message\":{\"payload\":\"payload\",\"description\":\"description\",\"timestamp\":\"Thu Jan 1 1970 01:00:00 GMT+0100\"},\"domain\":{\"name\":\"http://www.test.com\",\"version\":\"1.0\",\"chainId\":1,\"verifyingContract\":\"0x0123456789012345678901234567890123456789\",\"salt\":\"0x0000000000000000000000000000000000000000000000000000000000000000\"}}"}> but was: <{"signatureInHex":"0xbadb4457d349474db1e1b14414bcb0dbbba903d1d3ddd6c742aca9903a59b73567f314f41a13349d07f2519b07734406491a7f31810218a50757b1700f557bcd1c","jsonSigned":"{\"types\":{\"Test\":[{\"name\":\"payload\",\"type\":\"string\"},{\"name\":\"description\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":\"string\"}],\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"},{\"name\":\"verifyingContract\",\"type\":\"address\"},{\"name\":\"salt\",\"type\":\"bytes32\"}]},\"primaryType\":\"Test\",\"message\":{\"payload\":\"payload\",\"description\":\"description\",\"timestamp\":\"Thu Jan 1 1970 10:00:00 GMT+1000\"},\"domain\":{\"name\":\"http://www.test.com\",\"version\":\"1.0\",\"chainId\":1,\"verifyingContract\":\"0x0123456789012345678901234567890123456789\",\"salt\":\"0x0000000000000000000000000000000000000000000000000000000000000000\"}}"}>
Expected :{"signatureInHex":"0x71d1b3925bcc1482e34f4ae6f5560e27e6a7f3ad48acefb8089f3d450b3b6e225f28d2a73f1b08956e5b75c5ff0552e251492b493849aac8f4a9cd8cc54bee231c","jsonSigned":"{\"types\":{\"Test\":[{\"name\":\"payload\",\"type\":\"string\"},{\"name\":\"description\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":\"string\"}],\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"},{\"name\":\"verifyingContract\",\"type\":\"address\"},{\"name\":\"salt\",\"type\":\"bytes32\"}]},\"primaryType\":\"Test\",\"message\":{\"payload\":\"payload\",\"description\":\"description\",\"timestamp\":\"Thu Jan 1 1970 01:00:00 GMT+0100\"},\"domain\":{\"name\":\"http://www.test.com\",\"version\":\"1.0\",\"chainId\":1,\"verifyingContract\":\"0x0123456789012345678901234567890123456789\",\"salt\":\"0x0000000000000000000000000000000000000000000000000000000000000000\"}}"}
Actual   :{"signatureInHex":"0xbadb4457d349474db1e1b14414bcb0dbbba903d1d3ddd6c742aca9903a59b73567f314f41a13349d07f2519b07734406491a7f31810218a50757b1700f557bcd1c","jsonSigned":"{\"types\":{\"Test\":[{\"name\":\"payload\",\"type\":\"string\"},{\"name\":\"description\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":\"string\"}],\"EIP712Domain\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":\"string\"},{\"name\":\"chainId\",\"type\":\"uint256\"},{\"name\":\"verifyingContract\",\"type\":\"address\"},{\"name\":\"salt\",\"type\":\"bytes32\"}]},\"primaryType\":\"Test\",\"message\":{\"payload\":\"payload\",\"description\":\"description\",\"timestamp\":\"Thu Jan 1 1970 10:00:00 GMT+1000\"},\"domain\":{\"name\":\"http://www.test.com\",\"version\":\"1.0\",\"chainId\":1,\"verifyingContract\":\"0x0123456789012345678901234567890123456789\",\"salt\":\"0x0000000000000000000000000000000000000000000000000000000000000000\"}}"}
````

**Comment by jot2re** [comment]
@fyang1024 discovered the issue was in fact related to local time-zone being used when constructing attestations. This should be fixed now.

**Pull request merged**
